---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: wordpress
spec:
   selector:
     matchLabels:
       app: wordpress
   strategy: 
     type: Recreate
   template: 
     metadata:
       labels:
         app: wordpress
     spec: 
       containers: 
       - image: mansurali901/wordpress:1.0.0
         name: wordpress
         ports:
         - containerPort: 80
           name: wordpress

